[module.hugoVersion]
extended = true
min = "0.127.0"

[[module.imports]]
path = "github.com/hugomods/snackbar"

[[module.imports]]
path = "github.com/hugomods/i18n-js"

[params.code_block_panel]
line_nos = true
max_lines = 10
wrap = false
