title = 'Hugo Code Block Panel Module'

[markup.highlight]
lineNos = true
lineNumbersInTable = false
# noClasses = false
style = "gruvbox"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-code-block-panel"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons/vendors/bootstrap"

[params.code_block_panel]
max_lines = 7
# line_nos = false
